In [1]:
import pandas as pd

In [2]:
plays = pd.read_csv('plays.csv')
plays.dtypes

gameId                      int64
playId                      int64
quarter                     int64
GameClock                  object
down                        int64
yardsToGo                   int64
possessionTeam             object
yardlineSide               object
yardlineNumber            float64
offenseFormation           object
personnel.offense          object
defendersInTheBox         float64
numberOfPassRushers       float64
personnel.defense          object
HomeScoreBeforePlay         int64
VisitorScoreBeforePlay      int64
HomeScoreAfterPlay          int64
VisitorScoreAfterPlay       int64
isPenalty                    bool
isSTPlay                     bool
SpecialTeamsPlayType       object
KickReturnYardage         float64
PassLength                float64
PassResult                 object
YardsAfterCatch           float64
PlayResult                  int64
playDescription            object
dtype: object

In [3]:
plays_4th = plays[plays['down'] == 4]

In [4]:
fourth_down = plays_4th[plays_4th['isSTPlay'] == False]
fourth_down

,gameId,playId,quarter,GameClock,down,yardsToGo,possessionTeam,yardlineSide,yardlineNumber,offenseFormation,...,VisitorScoreAfterPlay,isPenalty,isSTPlay,SpecialTeamsPlayType,KickReturnYardage,PassLength,PassResult,YardsAfterCatch,PlayResult,playDescription
158,2017091004,4322,4,02:27:00,4,2,ARI,DET,30.0,SINGLEBACK,...,17,False,False,NaN,NaN,NaN,NaN,NaN,2,(2:27) (No Huddle) C.Palmer up the middle to D...
187,2017090700,653,1,09:34:00,4,1,NE,KC,10.0,SINGLEBACK,...,0,False,False,NaN,NaN,NaN,NaN,NaN,0,(9:34) N.Solder reported in as eligible. M.Gi...
307,2017090700,3874,4,12:29:00,4,1,NE,KC,40.0,JUMBO,...,28,False,False,NaN,NaN,NaN,NaN,NaN,0,(12:29) N.Solder reported in as eligible. M.G...
449,2017091003,2796,3,02:03:00,4,2,CLE,PIT,42.0,SHOTGUN,...,21,False,False,NaN,NaN,2.0,C,4.0,6,(2:03) (Shotgun) D.Kizer pass short left to S....
478,2017091003,3545,4,03:40:00,4,2,CLE,PIT,3.0,EMPTY,...,21,True,False,NaN,NaN,3.0,C,0.0,3,(3:40) (Shotgun) D.Kizer pass short left to C....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13839,2017101200,3996,4,03:33:00,4,2,CAR,PHI,45.0,EMPTY,...,28,False,False,NaN,NaN,2.0,C,2.0,4,(3:33) (Shotgun) C.Newton pass short left to C...
13851,2017101200,4297,4,01:22:00,4,1,CAR,PHI,48.0,SHOTGUN,...,28,False,False,NaN,NaN,8.0,I,NaN,0,(1:22) (Shotgun) C.Newton pass incomplete shor...
13966,2017101600,2803,4,15:00:00,4,1,TEN,IND,43.0,I_FORM,...,19,False,False,NaN,NaN,NaN,NaN,NaN,1,(15:00) M.Mariota up the middle to IND 42 for ...
13999,2017101600,3636,4,02:26:00,4,1,IND,TEN,13.0,I_FORM,...,22,False,False,NaN,NaN,NaN,S,NaN,0,(2:26) J.Brissett sacked at TEN 13 for 0 yards...
14148,2017101501,3594,4,06:31:00,4,1,BAL,CHI,32.0,I_FORM,...,17,False,False,NaN,NaN,NaN,NaN,NaN,2,(6:31) J.Allen left guard to CHI 30 for 2 yard...

In [5]:
fourth_down.loc[fourth_down['yardsToGo'] <= fourth_down['PlayResult'], 'firstDown_Conversion'] = 1 
fourth_down.loc[fourth_down['yardsToGo'] > fourth_down['PlayResult'], 'firstDown_Conversion'] = 0

fourth_down.columns

fourth_down

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1599: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,gameId,playId,quarter,GameClock,down,yardsToGo,possessionTeam,yardlineSide,yardlineNumber,offenseFormation,...,isPenalty,isSTPlay,SpecialTeamsPlayType,KickReturnYardage,PassLength,PassResult,YardsAfterCatch,PlayResult,playDescription,firstDown_Conversion
158,2017091004,4322,4,02:27:00,4,2,ARI,DET,30.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(2:27) (No Huddle) C.Palmer up the middle to D...,1.0
187,2017090700,653,1,09:34:00,4,1,NE,KC,10.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(9:34) N.Solder reported in as eligible. M.Gi...,0.0
307,2017090700,3874,4,12:29:00,4,1,NE,KC,40.0,JUMBO,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(12:29) N.Solder reported in as eligible. M.G...,0.0
449,2017091003,2796,3,02:03:00,4,2,CLE,PIT,42.0,SHOTGUN,...,False,False,NaN,NaN,2.0,C,4.0,6,(2:03) (Shotgun) D.Kizer pass short left to S....,1.0
478,2017091003,3545,4,03:40:00,4,2,CLE,PIT,3.0,EMPTY,...,True,False,NaN,NaN,3.0,C,0.0,3,(3:40) (Shotgun) D.Kizer pass short left to C....,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13839,2017101200,3996,4,03:33:00,4,2,CAR,PHI,45.0,EMPTY,...,False,False,NaN,NaN,2.0,C,2.0,4,(3:33) (Shotgun) C.Newton pass short left to C...,1.0
13851,2017101200,4297,4,01:22:00,4,1,CAR,PHI,48.0,SHOTGUN,...,False,False,NaN,NaN,8.0,I,NaN,0,(1:22) (Shotgun) C.Newton pass incomplete shor...,0.0
13966,2017101600,2803,4,15:00:00,4,1,TEN,IND,43.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,1,(15:00) M.Mariota up the middle to IND 42 for ...,1.0
13999,2017101600,3636,4,02:26:00,4,1,IND,TEN,13.0,I_FORM,...,False,False,NaN,NaN,NaN,S,NaN,0,(2:26) J.Brissett sacked at TEN 13 for 0 yards...,0.0
14148,2017101501,3594,4,06:31:00,4,1,BAL,CHI,32.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(6:31) J.Allen left guard to CHI 30 for 2 yard...,1.0

In [6]:
fourth_down

,gameId,playId,quarter,GameClock,down,yardsToGo,possessionTeam,yardlineSide,yardlineNumber,offenseFormation,...,isPenalty,isSTPlay,SpecialTeamsPlayType,KickReturnYardage,PassLength,PassResult,YardsAfterCatch,PlayResult,playDescription,firstDown_Conversion
158,2017091004,4322,4,02:27:00,4,2,ARI,DET,30.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(2:27) (No Huddle) C.Palmer up the middle to D...,1.0
187,2017090700,653,1,09:34:00,4,1,NE,KC,10.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(9:34) N.Solder reported in as eligible. M.Gi...,0.0
307,2017090700,3874,4,12:29:00,4,1,NE,KC,40.0,JUMBO,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(12:29) N.Solder reported in as eligible. M.G...,0.0
449,2017091003,2796,3,02:03:00,4,2,CLE,PIT,42.0,SHOTGUN,...,False,False,NaN,NaN,2.0,C,4.0,6,(2:03) (Shotgun) D.Kizer pass short left to S....,1.0
478,2017091003,3545,4,03:40:00,4,2,CLE,PIT,3.0,EMPTY,...,True,False,NaN,NaN,3.0,C,0.0,3,(3:40) (Shotgun) D.Kizer pass short left to C....,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13839,2017101200,3996,4,03:33:00,4,2,CAR,PHI,45.0,EMPTY,...,False,False,NaN,NaN,2.0,C,2.0,4,(3:33) (Shotgun) C.Newton pass short left to C...,1.0
13851,2017101200,4297,4,01:22:00,4,1,CAR,PHI,48.0,SHOTGUN,...,False,False,NaN,NaN,8.0,I,NaN,0,(1:22) (Shotgun) C.Newton pass incomplete shor...,0.0
13966,2017101600,2803,4,15:00:00,4,1,TEN,IND,43.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,1,(15:00) M.Mariota up the middle to IND 42 for ...,1.0
13999,2017101600,3636,4,02:26:00,4,1,IND,TEN,13.0,I_FORM,...,False,False,NaN,NaN,NaN,S,NaN,0,(2:26) J.Brissett sacked at TEN 13 for 0 yards...,0.0
14148,2017101501,3594,4,06:31:00,4,1,BAL,CHI,32.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(6:31) J.Allen left guard to CHI 30 for 2 yard...,1.0

In [7]:
fourth_down.to_csv('plays_4thdowns.csv')

In [8]:
df_2019 = pd.read_csv('reg_pbp_2019.csv')

In [9]:
df_2019_clean = df_2019.loc[:,['home_team','away_team', 'defteam', 'yardline_100', 'fourth_down_converted', 'pass_length', 'penalty', 'down', 'yards_after_catch', 'play_type', 'game_seconds_remaining', 'air_yards','total_home_score', 'total_away_score','ydstogo','yards_gained']]

In [10]:
df_2019_clean

,home_team,away_team,defteam,yardline_100,fourth_down_converted,pass_length,penalty,down,yards_after_catch,play_type,game_seconds_remaining,air_yards,total_home_score,total_away_score,ydstogo,yards_gained
0,CHI,GB,GB,33.0,0.0,NaN,0.0,4.0,NaN,run,1140.0,NaN,3,7,10,3
1,CHI,GB,GB,84.0,0.0,NaN,0.0,4.0,NaN,pass,69.0,NaN,3,10,8,-11
2,PHI,WAS,WAS,29.0,0.0,short,0.0,4.0,NaN,pass,2452.0,0.0,0,10,2,0
3,PHI,WAS,WAS,66.0,1.0,NaN,0.0,4.0,NaN,run,1683.0,NaN,7,20,1,2
4,PHI,WAS,PHI,59.0,1.0,short,0.0,4.0,2.0,pass,146.0,6.0,32,20,7,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,DEN,OAK,DEN,45.0,1.0,short,0.0,4.0,0.0,pass,42.0,11.0,16,9,2,11
584,LA,ARI,ARI,83.0,0.0,NaN,0.0,4.0,NaN,run,2985.0,NaN,3,0,7,6
585,SEA,SF,SF,31.0,0.0,NaN,0.0,4.0,NaN,run,1849.0,NaN,0,13,1,0
586,SEA,SF,SF,12.0,1.0,short,0.0,4.0,0.0,pass,42.0,11.0,21,26,10,11
587,SEA,SF,SF,5.0,0.0,short,0.0,4.0,0.0,pass,12.0,4.0,21,26,5,4

In [11]:
df_2019_fourth = df_2019_clean[df_2019_clean['down'] == 4]
df_2019_fourth['play_type'] = df_2019_fourth['play_type'].astype(str)

In [12]:
df_2019_fourth = df_2019_fourth[(df_2019_fourth['play_type'] == 'run') | (df_2019_fourth['play_type'] == 'pass')]

In [13]:
df_2019_fourth['year'] =2019

In [14]:
#adam start here

In [15]:
generated_data = pd.read_csv('generated_data.csv')

In [16]:
df_2019_fourth

,home_team,away_team,defteam,yardline_100,fourth_down_converted,pass_length,penalty,down,yards_after_catch,play_type,game_seconds_remaining,air_yards,total_home_score,total_away_score,ydstogo,yards_gained,year
0,CHI,GB,GB,33.0,0.0,NaN,0.0,4.0,NaN,run,1140.0,NaN,3,7,10,3,2019
1,CHI,GB,GB,84.0,0.0,NaN,0.0,4.0,NaN,pass,69.0,NaN,3,10,8,-11,2019
2,PHI,WAS,WAS,29.0,0.0,short,0.0,4.0,NaN,pass,2452.0,0.0,0,10,2,0,2019
3,PHI,WAS,WAS,66.0,1.0,NaN,0.0,4.0,NaN,run,1683.0,NaN,7,20,1,2,2019
4,PHI,WAS,PHI,59.0,1.0,short,0.0,4.0,2.0,pass,146.0,6.0,32,20,7,8,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,DEN,OAK,DEN,45.0,1.0,short,0.0,4.0,0.0,pass,42.0,11.0,16,9,2,11,2019
584,LA,ARI,ARI,83.0,0.0,NaN,0.0,4.0,NaN,run,2985.0,NaN,3,0,7,6,2019
585,SEA,SF,SF,31.0,0.0,NaN,0.0,4.0,NaN,run,1849.0,NaN,0,13,1,0,2019
586,SEA,SF,SF,12.0,1.0,short,0.0,4.0,0.0,pass,42.0,11.0,21,26,10,11,2019
587,SEA,SF,SF,5.0,0.0,short,0.0,4.0,0.0,pass,12.0,4.0,21,26,5,4,2019

In [17]:
fourth_down

,gameId,playId,quarter,GameClock,down,yardsToGo,possessionTeam,yardlineSide,yardlineNumber,offenseFormation,...,isPenalty,isSTPlay,SpecialTeamsPlayType,KickReturnYardage,PassLength,PassResult,YardsAfterCatch,PlayResult,playDescription,firstDown_Conversion
158,2017091004,4322,4,02:27:00,4,2,ARI,DET,30.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(2:27) (No Huddle) C.Palmer up the middle to D...,1.0
187,2017090700,653,1,09:34:00,4,1,NE,KC,10.0,SINGLEBACK,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(9:34) N.Solder reported in as eligible. M.Gi...,0.0
307,2017090700,3874,4,12:29:00,4,1,NE,KC,40.0,JUMBO,...,False,False,NaN,NaN,NaN,NaN,NaN,0,(12:29) N.Solder reported in as eligible. M.G...,0.0
449,2017091003,2796,3,02:03:00,4,2,CLE,PIT,42.0,SHOTGUN,...,False,False,NaN,NaN,2.0,C,4.0,6,(2:03) (Shotgun) D.Kizer pass short left to S....,1.0
478,2017091003,3545,4,03:40:00,4,2,CLE,PIT,3.0,EMPTY,...,True,False,NaN,NaN,3.0,C,0.0,3,(3:40) (Shotgun) D.Kizer pass short left to C....,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13839,2017101200,3996,4,03:33:00,4,2,CAR,PHI,45.0,EMPTY,...,False,False,NaN,NaN,2.0,C,2.0,4,(3:33) (Shotgun) C.Newton pass short left to C...,1.0
13851,2017101200,4297,4,01:22:00,4,1,CAR,PHI,48.0,SHOTGUN,...,False,False,NaN,NaN,8.0,I,NaN,0,(1:22) (Shotgun) C.Newton pass incomplete shor...,0.0
13966,2017101600,2803,4,15:00:00,4,1,TEN,IND,43.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,1,(15:00) M.Mariota up the middle to IND 42 for ...,1.0
13999,2017101600,3636,4,02:26:00,4,1,IND,TEN,13.0,I_FORM,...,False,False,NaN,NaN,NaN,S,NaN,0,(2:26) J.Brissett sacked at TEN 13 for 0 yards...,0.0
14148,2017101501,3594,4,06:31:00,4,1,BAL,CHI,32.0,I_FORM,...,False,False,NaN,NaN,NaN,NaN,NaN,2,(6:31) J.Allen left guard to CHI 30 for 2 yard...,1.0

In [18]:
generated_data

,Unnamed: 0,Unnamed: 0.1,down,quarter,yardsToGo,yardlineNumber,defendersInTheBox,numberOfPassRushers,HomeScoreBeforePlay,HomeScoreAfterPlay,VisitorScoreBeforePlay,VisitorScoreAfterPlay,PassLength,YardsAfterCatch,PlayResult,firstDown_Conversion,yardline_half
0,0,0,4,2,4,4,5,5,0,0,10,17,2,2,4,0,46
1,1,1,4,3,7,21,3,2,6,6,17,17,4,2,6,0,29
2,2,2,4,4,10,5,7,5,42,42,0,0,3,0,3,0,45
3,3,3,4,1,2,42,6,2,10,10,0,0,1,4,5,1,8
4,4,4,4,2,1,43,5,2,24,24,7,7,1,2,3,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,99995,4,4,1,13,6,4,7,7,24,24,2,3,5,1,37
99996,99996,99996,4,2,2,12,7,5,3,3,13,13,1,2,3,1,38
99997,99997,99997,4,4,9,5,6,5,14,14,34,34,4,2,6,0,45
99998,99998,99998,4,2,1,6,5,4,24,24,7,7,5,1,6,1,44
99999,99999,99999,4,2,2,6,4,3,0,7,20,20,3,3,6,1,44

In [19]:
import numpy as np

minutes = np.array(df_2019_fourth['game_seconds_remaining'] // 60).astype(int)
seconds = np.array(df_2019_fourth['game_seconds_remaining'] % 60).astype(int)
GameClock = []
for i in range(len(minutes)):
    GameClock.append(f'{minutes[i]}:{str(seconds[i]).zfill(2)}:00')

In [20]:
df_2019_fourth['GameClock'] = GameClock

In [21]:
df_2019_fourth['yardline_half'] = df_2019_fourth['yardline_100'].apply(lambda x: 50 - x if x < 50 else x - 50)

In [22]:
df_2019_fourth['score_diff'] = df_2019_fourth['total_home_score'] - df_2019_fourth['total_away_score']

In [23]:
generated_data['yardline_half'] = generated_data['yardlineNumber'].apply(lambda x: 50 - x if x < 50 else x - 50)

In [24]:
generated_data.to_csv('generated_data.csv')

In [25]:
fourth_down['score_diff'] = fourth_down['HomeScoreBeforePlay'] - fourth_down['VisitorScoreBeforePlay']

<ipython-input-25-d42f28f26996>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fourth_down['score_diff'] = fourth_down['HomeScoreBeforePlay'] - fourth_down['VisitorScoreBeforePlay']

In [29]:
from datetime import timedelta

def seconder(x):
    mins, secs, millis = map(float, x.split(':'))
    td = timedelta(minutes=mins, seconds=secs, milliseconds=millis)
    return td.total_seconds()

In [31]:
fourth_down['game_seconds_remaining'] = fourth_down['GameClock'].apply(seconder)

<ipython-input-31-e77838d2c063>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fourth_down['game_seconds_remaining'] = fourth_down['GameClock'].apply(seconder)

In [32]:
fourth_down.to_csv('plays_4thdowns.csv')
df_2019_fourth.to_csv('reg_pbp_2019.csv')